### ISSUE TITLE
Doesn't work with tailwind 3.3.0+

### ISSUE THREAD

**Issue by xt0rted** [await-ovo/tailwindcss-webpack-plugin#12]
As of tailwind 3.3.0 [`getModuleDependencies`](https://github.com/tailwindlabs/tailwindcss/blob/cc1eec68720e168fca611956aac527575e6dd5ec/src/lib/getModuleDependencies.js#L75-L78) returns a `Set` not an array, so calling `.map()` on it's result throws.

https://github.com/await-ovo/tailwindcss-webpack-plugin/blob/e5f76edb9dc42a8e547e758ec61f11035815b99e/packages/utils/src/index.ts#L108

I think a backwards compatible fix would be to switch that line to:

```js
const deps = [...getModuleDependencies(configPath)].map(({ file }) => file);
```

**Comment by await-ovo** [comment]
Thanks for your report, It looks like the changes brought in from this [PR](https://github.com/tailwindlabs/tailwindcss/commit/7e9a53f6cbf17456423a201d3c3d1220801a733f#diff-0c881c6f17d784daf950c8b64eb5c9f1bcc195a1a78338a970ed457d98845e28). I'll fix it  now~

**Comment by await-ovo** [comment]
Hi, `tailwindcss-webpack-plugin@v0.0.12` released, should work fine now ~
