### ISSUE TITLE
npm i -D  tailwindcss-vite-plugin gives ERESOLVE unable to resolve dependency tree

### ISSUE THREAD

**Issue by pgforefront** [await-ovo/tailwindcss-webpack-plugin#6]
Hi, I'm trying to install this plugin but npm complains about the following:

   ~/r/f/vite-01  on   main !1  npm i -D tailwindcss-vite-plugin             ✔  at 15:09:41  
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: vite-01@0.0.0
npm ERR! Found: vite@4.1.4
npm ERR! node_modules/vite
npm ERR!   dev vite@"^4.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^3.1.7" from tailwindcss-vite-plugin@0.0.3
npm ERR! node_modules/tailwindcss-vite-plugin
npm ERR!   dev tailwindcss-vite-plugin@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/xyz/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xyz/.npm/_logs/2023-03-14T14_10_08_966Z-debug-0.log

    ~/r/f/vite-01  on   main !1      

I should not need to use --force, or --legacy-peer-deps, correct? Should this be fixed upstream?

Thanks!

**Comment by await-ovo** [comment]
Hi @pgforefront , this should be fixed now, you can try to install again, thanks~

**Comment by pgforefront** [comment]
Installing via npm works now  🥳 Thanks!

**Comment by await-ovo** [comment]
> Installing via npm works now  🥳 Thanks!

feel free to open any issues if you have any problems during using it☺️

**Comment by pgforefront** [comment]
Did a quick test in Chrome DevTools and it works as expected 👍😎
